### ISSUE TITLE
New release checklist for [version number]

### ISSUE THREAD

**Issue by ghapz120** [getsentry/action-release#106]
You can see the action released in [here](https://github.com/marketplace/actions/sentry-release).

Checklist for a new release:

- [x] Create a PR that bumps the version in `package.json` and merge it
- [x] Once merged, visit the [releases page](https://github.com/getsentry/action-release/releases)
  - [x] Create a new release
  - [x] Name the release (You can use the version number if you want)
  - [x] Describe the release by looking at what commits landed on master since the last release
  - Create a new tag by entering it in the drop down
    - [x] If it's a security update, tag is a patch release
    - [x] If it's just some improvements or bug fix, tag is a minor release
    - [x] If there are _breaking_ changes, tag it as a major release
      - [ ] Figure out if we need to do an external annoucement of sorts
- [x] Once published, visit [the marketplace](https://github.com/marketplace/actions/sentry-release) to see that the release is showing up

**Comment by ghapz120** [comment]
> You can see the action released in [here](https://github.com/marketplace/actions/sentry-release).
> 
> Checklist for a new release:
> 
>     * [ ]  Create a PR that bumps the version in `package.json` and merge it
> 
>     * [ ]  Once merged, visit the [releases page](https://github.com/getsentry/action-release/releases)
>       
>       * [ ]  Create a new release
>       * [ ]  Name the release (You can use the version number if you want)
>       * [ ]  Describe the release by looking at what commits landed on master since the last release
>       * Create a new tag by entering it in the drop down
>         
>         * [ ]  If it's a security update, tag is a patch release
>         * [ ]  If it's just some improvements or bug fix, tag is a minor release
>         * [ ]  If there are _breaking_ changes, tag it as a major release
>           
>           * [ ]  Figure out if we need to do an external annoucement of sorts
> 
>     * [ ]  Once published, visit [the marketplace](https://github.com/marketplace/actions/sentry-release) to see that the release is showing up

**Comment by ghapz120** [comment]
* [ ]  Create a PR that bumps the version in `package.json` and merge it

* [ ]  Once merged, visit the [releases page](https://github.com/getsentry/action-release/releases)
  
  * [ ]  Create a new release
  * [ ]  Name the release (You can use the version number if you want)
  * [ ]  Describe the release by looking at what commits landed on master since the last release
  * Create a new tag by entering it in the drop down
    
    * [ ]  If it's a security update, tag is a patch release
    * [ ]  If it's just some improvements or bug fix, tag is a minor release
    * [ ]  If there are _breaking_ changes, tag it as a major release
      
      * [ ]  Figure out if we need to do an external annoucement of sorts

* [ ]  Once published, visit [the marketplace](https://github.com/marketplace/actions/sentry-release) to see that the release is showing up
