### ISSUE TITLE
Road Map 2025 🎉

### ISSUE THREAD

**Issue by smeubank** [getsentry/action-release#207]
This GitHub action needs to attention! The following is a proposal for a roadmap on how we can update this action to provide more value to existing and new developers.

# Sentry GitHub Action Roadmap

## Overview

This document outlines the strategic roadmap for Sentry's GitHub Action that handles release management, source file uploads, and source map processing. The goal is to modernize the action while expanding its capabilities and platform support.

### 1. Action Telemetry

**Priority: high**

Sentry errors, transactions with tags, and session
  - avoid PII (no stack traces)
  - dashboard 
  - add opt-out mechanism 
  - Download or run stats (not built in)
  - User-agent verify how this is being set 

- Use data to inform:
    - Feature prioritization
    - Bug detection and resolution
    - Documentation improvements
    - Platform support decisions
    - allow for dogfooding of sentry errors with static analysis

   

### 2. Debug ID Integration

**Priority: High**

- Implement debugID injection functionality == expose —inject
- 1st: make inject opt-in - they need to configure
- 2nd: we need to decide if we can opt in by default without a new major
    - if we do need a major, we need to consider migration tools → codemod
    - we may also consider changing the name of the action
      - Ideally updates could be backward compatible some how, and if we do have a new name/action then let's try to get debugIds out first, to increase the likelihood for orgs with the existing action name configured as much as possible

### 3. Investigate how use  to sentry-cli v2 better

**Priority: High**

- Update GHA to use sentry-cli v2: this done ✅
    - Ensure backward compatibility during transition
- **Onboarding and docs usage**: Update documentation to reflect v2 usage
    - learnings from codecov GHA oboarding: [**[Code Coverage](https://www.notion.so/Code-Coverage-11c8b10e4b5d80bca88af453866ab3d3?pvs=21)**](https://www.notion.so/Code-Coverage-11c8b10e4b5d80bca88af453866ab3d3?pvs=21)
    - https://docs.sentry.io/product/releases/setup/release-automation/github-actions/
- Evaluate and implement relevant new CLI v2 features
- Consider supporting:
    - Enhanced release management capabilities
        - MFE source maps support
    - Improved source map processing
    - New authentication methods
    - Performance optimization options

### 4. Action Onboarding    

- Improve wizard suppor
    1. argument/shortcut for -github-actions 
    2. `npx @sentry/wizard@latest -i sourcemaps --github-action`
    3. could be done for all tools
    4. inject and potentially update GitHub workflow file in target repo

- Improve the [existing docs ](https://docs.sentry.io/product/releases/setup/release-automation/github-actions/)
  - Need to be more descriptive and include an example of the golden path config, and most popular options

### 5. Multi-Platform/Language Support

**Priority: Medium**

- Extend beyond JavaScript/TypeScript
- Add support for:
    - Python source maps
    - Java source files
    - .NET debug symbols
    - Rust debug information
    - Arguably improved support for TS
- Create language-specific documentation
- We should talk with Jasmin and Bruno about the [releases product](https://www.notion.so/sentry/Release-Health-Proposal-to-Address-Core-Challenges-in-the-Current-Experience-and-Streamline-the-UI-1278b10e4b5d8070b288ed601b27c015?pvs=4) experience

### 6. Cross-OS Compatibility

**Priority: Low**

- Ensure reliable operation on:
    - Ubuntu/Linux
    - Windows
    - macOS
- Implement OS-specific optimizations
- Add CI testing across platforms

### 7. Update Develop Docs

**Priority: Low**

- We have some internal specification docs about the GHA, let;s make those public
    - [[Spec: GitHub Actions](https://www.notion.so/Spec-GitHub-Actions-7e5e38b205904becae30fcd76a2b4252?pvs=21)](https://www.notion.so/Spec-GitHub-Actions-7e5e38b205904becae30fcd76a2b4252?pvs=21)
- This should be done as we go, not in the end

### 8. Speak with other product teams

**Priority: Low**

- There are efforts to improve the releases product for more platforms
- Could the GitHub Action be uniquely positioned to help with that onboarding and adoption?

## Success Metrics

- Successful migration of existing users to debugIds
- Increased adoption across different programming languages
- Reduced issues related to source map processing
- Improved user satisfaction through GitHub feedback
- Higher success rate for source context uploads
- adoption across more platform
- increased successful usage of releases product 

## Timeline

- Q1: initial debugID support
- Q1: error monitoring & telemetry
- Q1: establish clear build and release strategy (naming and major decision)
- Q2: Enhanced language and OS support and documentation
- Q2: Improve arguments setting: a number of issues related to version setting for example
- QX: moar

```[tasklist]
### Tasks
- [x] error monitoring & telemetry
- [ ] https://github.com/getsentry/action-release/issues/206
- [x] cli v2 investigation
- [x] multi-platform/lanugage support
- [x] X-OS Support
```

**Comment by scefali** [comment]
@smeubank Love it! It's been almost a year since I made the last release. GH actions need some love :)

**Comment by mydea** [comment]
Closing this as I think the stuff we lined out here is done now @andreiborza ?
